// MODAL INSCRIPTIONvar modal = document.getElementById('modal');
var btni = document.getElementById('btni');
var btni1 = document.getElementById('btni1');
var btni2 = document.getElementById('btni2');
var btni3 = document.getElementById('btni3');function modalDisplay(){
	modal.style.display= "none";
}btni.onclick= function(){
	modal.style.display= "block";
}btni1.onclick= function(){
	modal.style.display= "block";
}btni2.onclick= function(){
	modal.style.display= "block";
}btni3.onclick= function(){
	modal.style.display= "block";
}btnNo.onclick= function(){
	modal.style.display= "none";
}btnNo2.onclick= function(){
	modal.style.display= "none";
}